In [1]:
import numpy as np

In [3]:
#1.
np.arange(12,38)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [92]:
#2.
x = np.ones((3,3))
print(x)
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
#3.
arr_ones = np.ones((3,3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# 4. Convert a list and tuple into arrays
lst = [1,2,3,4,5,6,7,8]
arr = np.array(lst)
print("List to array:",arr)
# Tuple to array
tup_arr =[8,4,6,1,2,3]
arr1 = np.array(tup_arr)
arr1 = arr1.reshape(2,3)
print("tuple to array:",arr1)

List to array: [1 2 3 4 5 6 7 8]
tuple to array: [[8 4 6]
 [1 2 3]]


In [25]:
#5. Convert the values of Centigrade degrees into Fahrenheit degrees
Fht=[ 0.,12.,45.21, 34.,99.91]
print("Values in Fahrenheit degrees",Fht)
Cls=[]
for a in Fht:
    b= ((a-32) *5)/9
    Cls.append(b)
print("Values in Celsius",Cls)

Values in Fahrenheit degrees [0.0, 12.0, 45.21, 34.0, 99.91]
Values in Celsius [-17.77777777777778, -11.11111111111111, 7.33888888888889, 1.1111111111111112, 37.727777777777774]


In [32]:
"""Write a NumPy program to find the number of elements of an array, 
length of one array element in bytes and total bytes consumed by the elements."""

arr = np.array(np.arange(1,4))
arr
print("Size ",arr.size)
print("Length of an array",arr.itemsize)
print("Total bytes consumed",arr.nbytes)


Size  3
Length of an array 4
Total bytes consumed 12


In [50]:
#Exercise 6: Get the unique elements of an array
arr1 = np.array([10,10,20,20,30,30])
arr1
unique_arr1 = np.unique(arr1)
print("Unique records arr1",unique_arr1)
arr2 =np.array([1,1,2,3])
arr2 = arr2.reshape(2,2)
unique_arr=np.unique(arr2)
print("unique records",unique_arr)

Unique records arr1 [10 20 30]
unique records [1 2 3]


In [54]:
#Change the dimension of an array
org_arr = np.array(np.arange(1,10))
org_arr
reshape_arr= org_arr.reshape(3,3)
print("dimension changed",reshape_arr)

dimension changed [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
lin_arr = np.array(np.linspace(2.5,6.5,30))
lin_arr

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

In [74]:
#Exercise 9: Convert 1-D arrays as columns into a 2-D array
arr1 =np.array([10,20,30])
arr2 = np.array([40,50,60])
np.column_stack((arr1,arr2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [80]:
#Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4
x = np.zeros((5,5))
x +=np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [83]:
x= np.arange(1,100)
res = x[((x%3==0) | (x%5==0))]
print("multiple of 3 or 5 ",res)
print("sum ",res.sum())


multiple of 3 or 5  [ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
sum  2318


In [87]:
#Exercise 12: Combine a one and a two dimensional array together and display their elements
arr1 = np.array(([0,1,2,3]))
arr2= np.array(([0,1,2,3],[4,5,6,7]))
print(arr1)
print(arr2)
for a, b in np.nditer([arr1,arr2]):
    print(a,":",b)
    

[0 1 2 3]
[[0 1 2 3]
 [4 5 6 7]]
0 : 0
1 : 1
2 : 2
3 : 3
0 : 4
1 : 5
2 : 6
3 : 7


In [88]:
#Write a NumPy program to replace all elements of NumPy array that are greater than specified array.
x = np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("Original array:")
print(x)
print("Replace all elements of the said array with .5 which are greater than .5")
x[x > .5] = .5
print(x)

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [90]:
arr = np.empty((0,3), int)
print("Empty array:")
print(arr)
arr = np.append(arr, np.array([[10,20,30]]), axis=0)
arr = np.append(arr, np.array([[40,50,60]]), axis=0)
print("After adding two new arrays:")
print(arr)

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


In [91]:
#Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis.
x = np.array([1, 2, 3])
y = np.array([2, 3, 4])
print("Original arrays:")
print(x)
print(y)
print("Sequence of arrays along a new axis:")
print(np.vstack((x, y)))
x = np.array([[1], [2], [3]])
y = np.array([[2], [3], [4]])
print("\nOriginal arrays:")
print(x)
print()
print(y)
print("Sequence of arrays along a new axis:")
print(np.vstack((x, y)))


Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
